import { JurisdictionConfig } from '../../shared/types';

export const MAS_SG: JurisdictionConfig = {
  id: 'MAS-SG',
  name: 'Monetary Authority of Singapore',
  description: 'Technology Risk Management Guidelines (TRMG) and Cyber Security Framework',
  security: {
    requireEncryption: true,
    approvedDependencies: [
      'aws-cdk-lib@^2.0',
      'express@^4.18',
      'react@^18.2',
      'typescript@^5.0',
    ],
    maxCveScore: 7.0,
    requireSecretsRotation: true,
  },
  architecture: {
    allowedRegions: ['ap-southeast-1', 'ap-southeast-2'],
    requireApiVersioning: true,
    requireMultiAz: true,
  },
  regulatory: {
    documentRiskClassification: true,
    requireHumanReview: true,
    requireAuditTrail: true,
  },
  materialityPatterns: {
    material: [
      'api.*contract',
      'auth.*flow',
      'data.*handling',
      'encryption',
      'risk.*class',
      'model.*registry',
      'payment.*flow',
      'compliance.*check',
      'audit.*trail',
      'customer.*data',
      'third-party.*integration',
      'core.*banking',
    ],
    routine: [
      '\\.css$',
      '\\.md$',
      '\\.txt$',
      '\\.png$',
      '\\.jpg$',
      '\\.svg$',
      '\\.json$',
      'config\\.yaml',
      'README',
      'CONTRIBUTING',
      '\\.github',
      'docs\\/',
      'assets\\/',
    ],
  },
};

export const EU_AI_ACT: JurisdictionConfig = {
  id: 'EU-AI-ACT',
  name: 'EU AI Act',
  description: 'European Union Artificial Intelligence Act (Article 6, Risk Classification)',
  security: {
    requireEncryption: true,
    approvedDependencies: [
      'aws-cdk-lib@^2.0',
      'express@^4.18',
      'react@^18.2',
      'typescript@^5.0',
    ],
    maxCveScore: 5.0,
    requireSecretsRotation: true,
  },
  architecture: {
    allowedRegions: ['eu-west-1', 'eu-central-1', 'eu-west-2'],
    requireApiVersioning: true,
    requireMultiAz: false,
  },
  regulatory: {
    documentRiskClassification: true,
    requireHumanReview: true,
    requireAuditTrail: true,
  },
  materialityPatterns: {
    material: [
      'model.*training',
      'model.*inference',
      'bias.*check',
      'fairness.*eval',
      'data.*governance',
      'high-risk.*system',
      'conformity.*assessment',
      'algorithm.*decision',
      'automated.*decision',
      'profiling',
      'credit.*scoring',
      'fraud.*detection',
    ],
    routine: [
      '\\.css$',
      '\\.md$',
      '\\.txt$',
      '\\.png$',
      '\\.jpg$',
      '\\.svg$',
      '\\.json$',
      'config\\.yaml',
      'README',
      'CONTRIBUTING',
      '\\.github',
      'docs\\/',
      'assets\\/',
    ],
  },
};

export const AU_APRA: JurisdictionConfig = {
  id: 'AU-APRA',
  name: 'APRA / ASIC Australia',
  description: 'CPS 234 Cyber Security, RG 274 Risk Management',
  security: {
    requireEncryption: true,
    approvedDependencies: [
      'aws-cdk-lib@^2.0',
      'express@^4.18',
      'react@^18.2',
      'typescript@^5.0',
    ],
    maxCveScore: 6.0,
    requireSecretsRotation: true,
  },
  architecture: {
    allowedRegions: ['ap-southeast-2', 'ap-southeast-4'],
    requireApiVersioning: true,
    requireMultiAz: true,
  },
  regulatory: {
    documentRiskClassification: true,
    requireHumanReview: true,
    requireAuditTrail: true,
  },
  materialityPatterns: {
    material: [
      'api.*contract',
      'auth.*flow',
      'data.*handling',
      'encryption',
      'risk.*class',
      'model.*registry',
      'payment.*flow',
      'compliance.*check',
      'audit.*trail',
      'customer.*data',
      'third-party.*integration',
      'core.*banking',
      'anti-money.*laundering',
      'aml',
      'kyc',
    ],
    routine: [
      '\\.css$',
      '\\.md$',
      '\\.txt$',
      '\\.png$',
      '\\.jpg$',
      '\\.svg$',
      '\\.json$',
      'config\\.yaml',
      'README',
      'CONTRIBUTING',
      '\\.github',
      'docs\\/',
      'assets\\/',
    ],
  },
};

export const JURISDICTIONS: Record<string, JurisdictionConfig> = {
  'MAS-SG': MAS_SG,
  'EU-AI-ACT': EU_AI_ACT,
  'AU-APRA': AU_APRA,
};
